[global]
	server string = Samba %v on %L
	log level = 0

	use sendfile = yes
	min receivefile size = 16384
	aio read size = 16384
	aio write size = 16384
	read raw = yes
	write raw = yes
	getwd cache = yes
	oplocks = yes
	dead time = 15
	unix extensions = no
	strict locking = no

	guest ok = yes
	map to guest = bad user

#	disable printing
	load printers = no
	printing = bsd
	printcap name = /dev/null
	disable spoolss = yes
	
[SD]
	path = /mnt/MPD/SD
	read only = no
	
[USB]
	path = /mnt/MPD/USB
	read only = no
	dfree command = /srv/http/bash/smbdfree.sh
	